### ISSUE TITLE
Heltec T114 Companion unreliable execution of commands on Repeater via Remote Management

### ISSUE THREAD

**Issue by fvanson** [meshcore-dev/MeshCore#947]
Heltec T114 Companion (FW 1.9.0) is not always reliably executing commands at Repeaters with connection via Remote Management. For instance, Request Status, getting setting of the Repeater, or requesting the sending oj an Advert is not possible in first approx. 10 seconds and request will time out. Also giving command in CLI is simply not executed. After 10 seconds it does execute, but it is not consistent as too often it does nothing or times out 
When doing the same via a Heltec V3 Companion I do not have this problem, so looks isolated to T114.
See also enclosed print screens.

<img width="1080" height="2400" alt="Image" src="https://github.com/user-attachments/assets/326dae52-f33c-4b8a-b022-6a842c836927" />

<img width="1080" height="2400" alt="Image" src="https://github.com/user-attachments/assets/7dd3d2c4-7d9d-480c-99a7-060df4759607" />

**Comment by IoTThinks** [comment]
I see it recently in my Heltec v3 too. 
After v1.8.1.

I thought due to bad signal.

**Comment by sblandford** [comment]
I am unable to admin either a Lilygo T-Echo repeaters or a RAK4361 repeater through a Lilygo T-Echo companion. I can log in but no CLI command works and any attempt to retrieve or change a setting results in a timeout. This is using both the USB and Bluetooth webapp, the Android App and the IOS App.

I was finally able to admin the RAK4361 repeater using another RAK4361 companion.

All these tests are at close range. No obvious errors in the debug log to report.

The firmware version is v1.10.0-0405e8b and the software version is v1.43 for the Android mobile app.

**Comment by oltaco** [comment]
This sounds like a well known issue that has existed for a long time. It looks like it is fixed in the current dev branch and will be in the next release.

**Comment by saradonim** [comment]
I still get timeouts during repeater remote management on the V1.11 release, making remote management impossible.

**Setup:**

- **Companion:** Lilygo T-Echo (Bluetooth). - Firmware V1.11
- **App:** Meshcore iOS App - Version 1.38.0
- **Repeater:** Seeed Studio SenseCap P1 PRO - Firmware V1.11

**Comment by recrof** [comment]
> I still get timeouts during repeater remote management on the V1.11 release, making remote management impossible.

oltaco mentioned dev/nightly, please flash and test: https://files.brazio.org/meshcore/nightly/

**Comment by saradonim** [comment]
> > I still get timeouts during repeater remote management on the V1.11 release, making remote management impossible.
> 
> oltaco mentioned dev/nightly, please flash and test: https://files.brazio.org/meshcore/nightly/

Yes, I can confirm that fixes the timeout issue on the Lilygo T-Echo. Thank you!

However, I still have a problem with Room Servers on the Lilygo T-Echo. It does connect successfully, but I can't leave any messages on the Room Server. It always says 'Failed' in the end...
