### ISSUE TITLE
RAK 4630 stopped working and lost all contacts after power reset

### ISSUE THREAD

**Issue by bmiguelbento** [meshcore-dev/MeshCore#979]
Today I lost my node from bluetooth and noticed that the blue LED was off - use to be on. I reset it first in the button and then with power. Then I was able to discover my node again trough bluetooth but lost all contacts. They are at "discovery contacts" but went away from my contacts list. Any thoughts on that? I have auto add contacts enable and I had about 120 contacts before it wiped out.

**Comment by jpds** [comment]
This one has probably been fixed by #972 and will be in the next firmware release.

**Comment by Narkoleptika** [comment]
Idk if this already made it into a release, but I'm having the same issue on 1.12.0

RAK 4630
lose BT connection
powercycle
reconnect
watch as contacts sync to 0

As op mentioned they are still in the discover screen, but when I try to add them back I make it about a third of the way through the list then lose BT again and the cycle repeats.

**Update**: I did a factory reset and that seems to have broken the cycle. It's unclear whether this will continue to be an intermittent problem though.

**Comment by Narkoleptika** [comment]
The factory reset allowed it to go for a day or so, but it eventually locked up again. Seems like it happens more frequently and severely the longer it's been since the last factory reset. At least once it's been bad enough that it would no longer boot and needed to be reflashed. For some reason, I don't lose contacts every time I reset it. Not sure if this is helpful info or not, but I noticed that the blue and green LEDs are continuously lit while it's frozen.

Oh and I'm on 1.13.0 now

**Comment by recrof** [comment]
@Narkoleptika what phone / OS version are you pairing your RAK with?

**Comment by Narkoleptika** [comment]
Pixel 7 pro / Android 16 (GrapheneOS, if that's relevant)

**Comment by weebl2000** [comment]
I think this is related to the adverts taking up space even with auto-add contacts on.

Should be fixed for any nodes running newer firmware from the start. For older companions this PR will fix the issue #1601 - if you are seeing your companion with nearly full storage please try PR #1601.

**Comment by dreimal8** [comment]
**The problem persists.**

Companion: RAK Starter kit - 19007 base board and RAK 4631
Firmware 1.14.1 and also 1.15.0
iPhone 11 with always the latest app version

When connecting via Bluetooth, sometimes the connection got stuck.
The device disappeared in the connection overview. The blue LED stays on – no flashing.
Turn it off and on again – device is available again and i can reconnect.
After connecting, the contacts count backwards to zero, and then the contact list is empty.

Happened on 2 different Companions - both RAK 4631

**Comment by dreimal8** [comment]
Problem still persists!
Latest iOS App version and 1.16

**Comment by dotspencer** [comment]
I've had multiple RAK 4631 companion nodes lock up like this on 1.16. Blue LED on solid and after using the reset button all contacts are lost. Going to test out 1.17 to see if that changes anything.

**Comment by Pawka** [comment]
Same problem.
- Device: MuziWorks R1 Neo (nRF52840)
- I think I was on v1.16. Auto-add contacts is enabled (disk space might be an issue, right?)
- Android. Latest app.

Last time it happened a couple of months ago on the same device - a few versions older firmware. When all contacts were deleted (after multiple reboots of device), the companion remained in a bad state still. Manually added contact was removed immediatelly, device disconnects from Bluetooth and needs to be restarted. Factory reset helped this time.
